### ISSUE TITLE
CityBee Prices API

### ISSUE THREAD

**Issue by dominik932500** [aanndryyyy/car-sharing-comparison#3]
Hello, you might be interested in this. You can access CityBee prices using this endpoint with header **Client: Selfservice**
`curl --location --request GET 'https://backend.citybee.ee/api/AvailableServices/Get' --header 'Client: SelfService'`
If you would like to check the prices in different countries, simply change the API endpoint to .lt, .lv or .ee.

**Comment by aanndryyyy** [comment]
@dominik932500 this is great, how did you discover that endpoint?

**Comment by dominik932500** [comment]
@aanndryyyy I found it here at line 48 https://github.com/2m/citywasp-api/blob/5b26d3dbb0da9f7fc158759073f1d778da1facbd/api/src/test/scala/ApiSuite.scala
